### ISSUE TITLE
Error running graf model

### ISSUE THREAD

**Issue by gaiteiro** [goldingn/gp_sdm_paper#1]
Running a set of model sincluding gp on the Dave Harris data, using the last available GRAF version from the CRAN archive, I get:

Error in checkForRemoteErrors(val) : 
  10 nodes produced errors; first error: no applicable method for 'predict' applied to an object of class "graf"

....perhaps because it's not expecting y to be a list object?

**Comment by goldingn** [comment]
Judging by the error message, it sounds like you didn't load GRaF with `library(GRaF)` before doing `predict()` on the GRaF model object in your parallel code.

**Comment by goldingn** [comment]
Oh sorry, I thought this was a Q on the main GRaF repo. If you are running the code as-is, then more likely it's due to the version of R you are using. S3 class dispatch rules seen to have changed at since point recently (from R 4.0 maybe?) so maybe try with an older version?

**Comment by goldingn** [comment]
If you'd rather patch up the code, you could change the predict line in the `*Fit()` functions that use GRaF from saying; `predict(...)` to saying: `GRaF::predict.graf(...)`, or something similar.

**Comment by gaiteiro** [comment]
Thanks! ....and sorry to be a nuisance. I'll have a go with R 4.0 in a minute (with GRaF::predict.graf I got "$ operator is invalid for atomic vectors")

**Comment by gaiteiro** [comment]
...actually that happens with R.4.0 too...

**Comment by goldingn** [comment]
Yes, I meant that it would have to be an earlier version than 4.0. probably more like 2.0-3.0 given how long ago I wrote this code!

**Comment by goldingn** [comment]
Oh, and you should also try using one of the versions of GRaF on GitHub - they are more recent than the Cran ones

**Comment by gaiteiro** [comment]
Thanks - with install_github('GRaF', 'goldingn') I got "Error in parse_repo_spec(repo) : Invalid git repo specification: 'GRaF'" - I installed the zip file from https://github.com/goldingn/GRaF instead- but as you say though, I get an error 'predict' is not an exported object from 'namespace:GRaF' for any R version from 3.4 onwards (I'm used to using RStudio which only works with these).

As a next step I'm trying older versions of R from the command line - admittedly nothing to report just yet as I first need to get gcc to work to install suitable (2012?) versions of sp and raster.

**Comment by gaiteiro** [comment]
Thanks - with install_github('GRaF', 'goldingn') I got "Error in parse_repo_spec(repo) : Invalid git repo specification: 'GRaF'" - I installed the zip file from https://github.com/goldingn/GRaF instead- but as you say though, I get an error 'predict' is not an exported object from 'namespace:GRaF' for any R version from 3.4 onwards (I'm used to using RStudio which only works with these).

As a next step I'm trying older versions of R from the command line - admittedly nothing to report just yet as I first need to get gcc to work to install suitable (2012?) versions of sp and raster.
